### PR TITLE
Bugs fix

### LINKED ISSUE #589: Bug Report: Unhandled exception "IndexError: list index out of range"
```
Commix version: 3.2-dev#53
Python version: 3.9.1
Operating system: posix
Command line: commix.py -u ******************************************
```
```
Traceback (most recent call last):
  File "request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "client.py", line 1010, in _send_output
    self.send(msg)
  File "client.py", line 950, in send
    self.connect()
  File "client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "ssl.py", line 1040, in _create
    self.do_handshake()
  File "ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1106: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests.py", line 52, in estimate_response_time
    response = _urllib.request.urlopen(request, timeout=settings.TIMEOUT)
  File "request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "request.py", line 517, in open
    response = self._open(req, data)
  File "request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "request.py", line 494, in _call_chain
    result = func(*args)
  File "request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error _ssl.c:1106: The handshake operation timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 913, in <module>
    main(filename, url)
  File "main.py", line 627, in main
    controller.do_check(url, filename)
  File "controller.py", line 686, in do_check
    perform_checks(url,filename)
  File "controller.py", line 610, in perform_checks
    basic_level_checks()
  File "controller.py", line 575, in basic_level_checks
    get_request(url, http_request_method, filename, timesec)
  File "controller.py", line 493, in get_request
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 142, in injection_proccess
    timesec, url_time_response = requests.estimate_response_time(url, timesec)
  File "requests.py", line 199, in estimate_response_time
    print(settings.print_critical_msg(str(err_msg.args[0]).split("] ")[1] + "."))
IndexError: list index out of range
```

### LINKED ISSUE #590: Bug report: Unhandled exception "TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'"
```
Commix version: 3.2-dev#53
Python version: 3.7.3
Operating system: posix
Command line: commix.py -u ************************** --all --shellshock

```
```
Traceback (most recent call last):
  File "shellshock.py", line 666, in shellshock_handler
    response = _urllib.request.urlopen(request, timeout=settings.TIMEOUT)
  File "request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "request.py", line 531, in open
    response = meth(req, response)
  File "request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "request.py", line 569, in error
    return self._call_chain(*args)
  File "request.py", line 503, in _call_chain
    result = func(*args)
  File "request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "commix.py", line 35, in <module>
    main()
  File "commix.py", line 30, in main
    import src.core.main
  File "main.py", line 913, in <module>
    main(filename, url)
  File "main.py", line 627, in main
    controller.do_check(url, filename)
  File "controller.py", line 686, in do_check
    perform_checks(url,filename)
  File "controller.py", line 616, in perform_checks
    stored_http_header_injection(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 390, in stored_http_header_injection
    http_headers_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 349, in http_headers_injection
    user_agent_injection(url, http_request_method, filename, timesec)
  File "controller.py", line 318, in user_agent_injection
    injection_proccess(url, check_parameter, http_request_method, filename, timesec)
  File "controller.py", line 144, in injection_proccess
    modules_handler.load_modules(url, http_request_method, filename)
  File "modules_handler.py", line 58, in load_modules
    shellshock.shellshock_handler(url, http_request_method, filename)
  File "shellshock.py", line 879, in shellshock_handler
    print("\n") + settings.print_critical_msg(err)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

### PR DESCRIPTION
**Pull request by shelld3v**
Fix #590, fix #589 and some linting

### CODE REVIEW

**Comment by stasinopoulos** [comment]
@shelld3v  due to fixes / updates that are scheduled to be pushed the following days, it could be useful to create a **separate PR** for each **unhanded exception** _(without the linting)_ in order to avoid conflicts.

**Review by stasinopoulos — COMMENTED** [review]
You have to update (via git) commix to the latest version (i.e. dev#56), perform the fixes and then create the PR.

**Comment by shelld3v** [comment]
I believe I resolved the conflicts! If you don't like it, you can close this, and commit by yourself, right?

**Comment by stasinopoulos** [comment]
> I believe I resolved the conflicts! If you don't like it, you can close this, and commit by yourself, right?

sure i can :) btw thanks for your effort on that :)

**Pull request closed without merging**
