### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JitPatro**
Not extensively tested as the original commix but it should work well.

@stasinopoulos Can you test the snap package when you've time?

### CODE REVIEW

**Comment by stasinopoulos** [comment]
Yaw @JitPatro  thanks for that, i ll check it out soon and i'll let you know. :)

**Comment by stasinopoulos** [comment]
I' ll extensively test the snap package and i 'll get back to you.

**Comment by JitPatro** [comment]
I think you didn't like it when I deleted your PR. I usually delete a **repo** if I had to make more than *five* edits in a day in that repo. I do this a lot. Honestly, I want your app to be a success because that'd mean my snap will be a success too! Keep up the great work. I like people who contribute towards open source, especially those contributing in **security**. Cheers!

**Comment by stasinopoulos** [comment]
Hello, @JitPatro the only reason that this PR has not been merged, is due to the fact that this is a "third party way" for downloading Commix. I added you [here](https://github.com/commixproject/commix/commit/6ab2d255773398b90ceeeb64c2cdef81b7b5c382) for your contribution, regarding snap package creation.

**Comment by JitPatro** [comment]
Thanks, I already saw that. I just didn't wanted you to feel bad about what I did. 🙂

**Pull request closed without merging**
