### PR TITLE
hot fix bad parsing when using -r

### PR DESCRIPTION
**Pull request by 0xFred**
when using -r and loading request from file extracted with zap proxy it messes up the domain read code comment for more info this hot fix fixes the issue but its ugly and can be doe much better at least it works using this code

### CODE REVIEW

**Comment by 0xFred** [comment]
i also removed some ugly spaces from random places in the file that don't serve any purpose but to add bytes to the file i am guessing it has something to do with the IDE that was used when creating this file and is prevalent all over the project

**Comment by stasinopoulos** [comment]
Hey @0xFred thanks for the PR. 
Kindly provide me with an example (e.g. sample request) in which current code fails, in order to check it and proceed with the merge of the PR.

**Comment by 0xFred** [comment]
this here should fail with code before this pr

`POST https://subdomain.domain.tld/includes/search.php HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.5
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0
Content-Type: application/x-www-form-urlencoded
Content-Length: 123
Host: subdomain.domain.tld

example=123
`

**Comment by 0xFred** [comment]
if you save that post req to /tmp/req.raw and use
python3 commix.py -r /tmp/req.raw
it will fail to parse the url pr fixes the issue but not the root cause

**Comment by stasinopoulos** [comment]
Cool, I'll check it out n' I'll let ya know.

**Comment by stasinopoulos** [comment]
@0xFred kindly update to the latest (dev) version and confirm my fix: https://github.com/commixproject/commix/commit/d1a35509b4fbf3453efd8b2851a2acce117b8b91

**Review by stasinopoulos — APPROVED** [review]

**Comment by 0xFred** [comment]
latest dev version is working correct

**Pull request closed without merging**
